language: java
os: linux
dist: xenial
jdk:
- openjdk8
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
script: mvn clean package -Dmaven.test.skip=true

branches:
  only:
  - main
notifications:
  email:
  - 1299193255@qq.com
